Add manual calculation of cc
slarse/lektor pull request #19
Opened 2019-02-12 20:53 UTC by rouwaydhanna

Add my answers to the manual calculation of cc and the drawings of condensation graphs with it.

#2

2019-02-12 21:55 UTC, larshum requested changes
There is a bit more work to be done.

Firstly, I think we should decide on one way to compute the CC. Perhaps we could state that we used different methods and describe what methods we used (this sounds more interesting to read, but less what they want).

Secondly, I think we need to add a description of each function, as I noted in my comment about line 27 in the `answers.md`. I think we should either split them in half or perhaps ask the others for help with that one (perhaps each of us can describe the methods we were assigned to write unit tests for).

Also, I didn't have time to look into the contents of the png's, but I will do that tomorrow and add one or more comments about that (to get the review started asap).

2019-02-12 21:55 UTC, larshum commented on report/manual_cc_count/rouwayd/answers.md
> +The CC is counted as CC = Number of decisions + 1.
In my calculations I used the formula presented during the lecture, which is similar, except it takes the number of exits (returns + raises) into account:

`CC = pi + s - 2`, where `pi = number of decisions` and `s = number of exits`

I think we should use that formula because it's the one from the lecture, but if you think this formula is better (I think it's more similar to what `lizard` uses) we can go with it instead.

2019-02-12 21:55 UTC, larshum commented on report/manual_cc_count/rouwayd/answers.md
> +CC = 7 (4 if, 2 for)
I got 7 here with the formula I used, which means our results were different for this one. The difference in this case is caused by the `and` operator, which according to the slides from the lecture counts as a decision.

I think it can be considered a decision because of the short circuit behavior (for `x and y`, if `x` is false then `y` is not evaluated).

2019-02-12 21:55 UTC, larshum commented on report/manual_cc_count/rouwayd/answers.md
> +CC = 9 (1 if, 2 for)
Here I found 4 if's, 2 for's, 1 while and one `or` condition, meaning a total of 8 decisions. But I got CC = 7 here because I took the three exits of this method into account (`CC = 8 - 3 + 2 = 7`).

No matter what we decide to use, we'll need to change what's inside the parentheses, because you cannot have gotten a CC of 9 from 1 if and 2 for's.

2019-02-12 21:55 UTC, larshum commented on report/manual_cc_count/rouwayd/answers.md
> +My results are not exactly the same as Lizard's output. There are some different things that are taken into account in Lizard's way of counting the CC compared to my way, such as boolean operators su
We should probably rewrite or add to this part, based on what we decide on. But I think the current version looks good for the method you used.

2019-02-12 21:55 UTC, larshum commented on report/manual_cc_count/rouwayd/answers.md
> +The documentation is very poor. Therefore, One must look at the function name or some statements in the function to learn the function purpose.
I think we are supposed to explicitly list what we interpret each of the functions do here, to fullfill requirement 4: `The purpose of each of the high-complexity methods is documented in detail w.r.t. the different outcomes resulting in branches in the code.`
We also need to discuss whether their purpose are related to them having a high CC.

2019-02-12 21:55 UTC, larshum commented on report/manual_cc_count/rouwayd/answers.md
> +A try-catch block should be taken into account when counting the CC. The code inside the catch block can be seen as a seperate branch as it will only be run if an exception is raised inside the try.
```suggestion
A try-catch block should be taken into account when counting the CC. The code inside the catch block can be seen as a separate branch as it will only be run if an exception is raised inside the try. With a strict interpretation, each statement inside the try could count as one decision since the exception could be raised anytime.
```

2019-02-12 21:55 UTC, larshum commented on report/manual_cc_count/rouwayd/answers.md
> +A try-catch block should be taken into account when counting the CC. The code inside the catch block can be seen as a seperate branch as it will only be run if an exception is raised inside the try.
I agree with the general idea here, just being a little picky :smile:

2019-02-12 21:55 UTC, larshum commented on report/manual_cc_count/rouwayd/answers.md
> +CC = 5 (3 if, 1 try-finally)
This seems to match my results, but in my interpretation of the method you used, the try-finally clause should not count as a decision (it only lists `catch`). Or am I misinterpreting it (which is likely, getting pretty sleepy by now :sleepy:).

2019-02-12 21:55 UTC, larshum commented on report/manual_cc_count/rouwayd/answers.md
> +High CC doesn't necessarily imply high ncloc. Of course there will be more decision making in high cc functions but there could be few non-decision making statements in the code, giving a low ncloc.
Sounds good overall, but the question asks if the functions are very long, so not explicitly about high ncloc.

2019-02-13 12:26 UTC, larshum commented on report/manual_cc_count/rouwayd/answers.md
> +CC = 7 (4 if, 2 for)
I hadn't read the later part, where you explain that you did not count the boolean operators, so I'm marking this conversation as resolved.

2019-02-13 13:10 UTC, larshum commented
About the PNG's:
* You have missed the `return` statement in the end of the try-statement `find_files`.
* The green arrow from `47` in `discover_relevant_flowblock_models` leads to `46`, but I think it should be named `48`.
* `content_file_info_cmd`:
  * The red arrow from `447` in `content_file_info_cmd` points to another box named `447`, but it should be named `449`.
  * The arrow from line `450` should go directly to `445`, since if the `if` condition has been met, the `elif` condition is not checked.
  * The red arrow pointing downwards from `460` should be green.
  * The if-statement on lines `463-464` are not included in the png.
  * When the if-statement on line `466` fails, it should point to the else-statement on line ` 472` which in turn points to lines `473-477`.
  * The block `479` should have a black arrow pointing back to `478` since it's the end of the for-loop.
* General feedback:
  * I think there should be some indication of which nodes are the exit nodes, as this is not always clear. For example, in `plugins_list_cmd`, the for-loop on 567 technically ends the method, so I think that block could be colored differently, point to a differently colored block or perhaps have an arrow which does not point to another block.
  * I think your images are better than the ones I produced because yours are easier to follow when looking at the code, so we should definitely use this format.

2019-02-17 10:53 UTC, rouwaydhanna commented
Will not be used.

2019-02-17 10:53 UTC, closed without merging