Add BranchTracer class
slarse/lektor pull request #35
Opened 2019-02-14 12:49 UTC by slarse

Adds a class called BranchTracer which traces execution of different branches. Lines with conditional statements must be pre-computed and provided to the constructor. One may also use the static factory method to produce a BranchTracer from one or more BranchFinders.

This is a large PR, but I could not find a way to split it up as either it all works, or nothing does.

A few lines of code in `conftest.py` (upcoming PR) will then allow us to track branching for our chosen functions.

Fix #12

2019-02-14 15:38 UTC, slarse commented
The build is failing because on Travis, `validator.py` finds the `__pycache__` directory with non `.py` files, and thus executes a branch I did not expect. Probably shouldn't have picked `validator.py` for testing here as it depends on the file system -.-. Can probably be solved by just adding some compiled python in `tests/coveragetool/sources/__pycache__` and change the expectations of the test.

2019-02-14 21:35 UTC, mnil2 requested changes
Good job. Just some points of confusion and a typo that I can see.

2019-02-14 21:35 UTC, martinnilsson93 commented on coveragetool/branchtracer.py
> +            del self._prev_line[frame]
Don't think this does anything since the prev line is set right after.

2019-02-14 21:35 UTC, martinnilsson93 commented on coveragetool/branchtracer.py
> +            (filepath ->
```suggestion
            (function_id ->
```
Simple mistake I assume.

2019-02-14 21:55 UTC, martinnilsson93 commented on coveragetool/branchtracer.py
> +            traced, otherwise None.
This Return section of the docstring appears wrong. The local tracefunction never returns None from what I can tell. Also, if we are in the local tracefunction the scope should always be traced, no?

2019-02-15 07:18 UTC, slarse commented on coveragetool/branchtracer.py
> +            del self._prev_line[frame]
Ah yes, it had an empty return before but I must have decided it wasn't to be there as it was a bit misleading ("return" is the last event in a scope anyway). Also why the docstring said it could return None.

2019-02-15 07:19 UTC, slarse commented on coveragetool/branchtracer.py
> +            (filepath ->
Yeah

2019-02-15 07:20 UTC, slarse commented on coveragetool/branchtracer.py
> +            traced, otherwise None.
The local tracefunction made some executive decisions before that it now doesn't (because I figured out exactly how the global and local functions play together). There was also an empty return if the event was "return", but that's a bit misleading as you can't trace after that anyway. So yes, that is wrong now.

2019-02-15 09:23 UTC, mnil2 approved these changes

2019-02-15 09:52 UTC, merged